name: Firebase Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: devdep
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust if needed

      - name: Install dependencies
        run: npm install

      - name: Build your app
        run: npm run build  # Replace with your build command

      - name: Login to Firebase
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          channelId: live  # Replace 'live' if you are deploying to a preview channel
          projectId: greenviewv2  # Replace with your Firebase project ID
