name: Firebase Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust if needed
      - name: Install dependencies
        run: npm install
      - name: Build your app
        run: npm run build  # Replace with your build command
      - name: Login to Firebase
        uses: firebase/action-gcp-auth@v0
        with:
          serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      - name: Deploy to Firebase Hosting
        uses: firebase/action-hosting-deploy@v0
        with:
          site: https://greenviewv2.firebaseapp.com  # Replace with your Firebase site name
          context: ./build  # Replace with your build output directory
          public: 'public'  # Replace if your build output directory is different
